#!/usr/bin/bash
syscalls=$1
timeout=$2
shift 2
exec /usr/local/lib/evalbot/playpen \
/opt/playpen \
--hostname=MISSINGNO. \
--mount-proc --user=eval \
--devices=/dev/urandom:r,/dev/null:rw,/dev/zero:rw \
--memory-limit=256 \
--tasks-max=256 \
--syscalls-file="$syscalls" \
--timeout="$timeout" \
--no-cloexec=3 \
--bringup-lo -- \
env LANG=$LANG "$@" 2>&1
